# Generated by Django 3.2.12 on 2024-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jinabase',
            name='x_value',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jinabase',
            name='y_value',
            field=models.CharField(max_length=250),
        ),
    ]
